const data = {
  'Data-structure': {
    books: [
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'd0ccf2b78322c69edae69c1de7b81914296eda47DS%20Book%202',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'dat-structure-and-algo-in-c++'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'data-sturcture-and-algo-and-puzzel',
      ],
    ],
    'hand-written': [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Array'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Deque'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Graphs'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Heaps'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Inorder-Traversal'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Intro'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Lecture-3-Matrix_-Stack-and-its-application',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Linked-List-intro'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Mid-Sem-Solutions'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Post-Order-Traversal'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'PreOrder-Traversal'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Queue'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Quick-Sort'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Recursive-Function'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Singly-Linked-List'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Stack-and-Queue'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Stack'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Tower-Of-Hanoi'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Tree-2'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Tree'],
    ],
    syllabus: [
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Data-Structure--B.Tech,-CSDA-2nd-Sem-Syllabus-',
      ],
    ],
    pyqs: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'data-end-2-sem-(2)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'data-end-2-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'data-end-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'data-mid-3-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'data-mid-sem'],
    ],
    yt: [
      [
        'unit1',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLPLmXWcXdkUMleZS9MsJ0VTe5nwM0B2JB',
      ],

      [
        'unit2',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLPLmXWcXdkUM47yfykGFEa8h4mQFg99RN',
      ],

      [
        'unit3',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLPLmXWcXdkUMCjzZZTUBtvkVRHkA3uZJx',
      ],

      [
        'unit4',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLPLmXWcXdkUOZSQtrsjm2i4uOzadM6tEH',
      ],
      [
        'unit5',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLPLmXWcXdkUPWOkJ9Xf1_CwmNEuLf7SU3',
      ],
    ],
  },
  Discrete: {
    books: [
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        "Discrete-Structure-Schaum's-outlines",
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'rosen_discrete_mathematics_and_its_applications_7th_edition',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Students-Solutions-Guide-to-accompany-Discrete-Mathematics-and-Its-Applications,-Seventh-Edition-(-etc.)-(Z-Library)',
      ],
    ],
    'hand-written': [
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Discrete-Mathematics---Probability',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        "Discrete-Structure-Schaum's-outlines",
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Discrete-U3'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Discrete_tutorial-(1)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Discrete_tutorial-(2)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Discrete_tutorial-(3)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DS-QB'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Numbertheory'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'practice-questions-logic'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Probability-Distributions'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'questions-pigen-pnc'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'recursive-function-'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        "Vishu's-Notes-Discrete-Structures",
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Vishu\u2019s-Short-Notes-DS'],
    ],
    syllabus: [['lorem ipsum', '19 Dec 2024', 'lorem', 'Discrete-Syllabus']],
    pyqs: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'dicrete-mid-2-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'dicrete-mid-23-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'discrete-end-2-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'discrete-end-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'discrete-mid-sem'],
    ],
    yt: [
      ['unit1', '19 Dec 2024', 'lorem', ''],

      [
        'unit2',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLL8qj6F8dGlTX359q-PBBUFw3BrBvAxq3',
      ],

      [
        'unit3',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PL9zFgBale5fvLZEn6ahrwDC2tRRipZQK0',
      ],

      ['unit4', '19 Dec 2024', 'lorem', ''],
      ['unit5', '19 Dec 2024', 'lorem', ''],
    ],
  },
  DLD: {
    books: [
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Digital-Design-With-an-Introduction-to-the-Verilog-HDL,-VHDL,-and-SystemVerilog-by-M.-Morris-R.-Mano--Michael-D.-Ciletti',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'DIGITAL-ELECTRONICS__Ashish-Murolia__R.-K.-Kanodia',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'digital-logic-and-computer-design-by-m-morris-mano-2nd-edition',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'DIGITAL-PRINCIPLES-AND-APPLICATION-BY-LEACH-_-MALVINO',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Digital-Systems-Design-Using-VHDL-(Charles-Roth)',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Digital-Systems-Design-Using-VHDL-by-Charles-H.-Roth,-Jr.,-Lizy-Kurian-John',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Digital-systems-design-with-VHDL-and-synthesis-by-K.-C.-Chang',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'digital_design-__morris_mano-fifth_edition',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Donald-D.-Givone__Chapter-8'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Modern-Digital-Electronics,-4th-Edition',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'roth-digital-system-design-with-vhdl-2007',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'VHDL-BY-Mc-GrawHill'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'vhdl-by-pearson'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'William-Stallings-Capter04'],
    ],
    'hand-written': [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Bjt-and-Op-Amp-short-notes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DCS-notes-2'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'dcs-notes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'vhdl-notes'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        "Vishu's-Notes-Digital-Logic-Design-(3)",
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Vishu\u2019s-Short-Notes-DLD'],
    ],
    syllabus: [['lorem ipsum', '19 Dec 2024', 'lorem', 'Syllabus_-DLD']],
    pyqs: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'dld-end-2-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DLD-end-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'dld-mid-2-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DLD-mid-sem'],
    ],
    yt: [
      [
        'unit1',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm',
      ],

      [
        'unit2',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm',
      ],

      [
        'unit3',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm',
      ],

      ['unit4', '19 Dec 2024', 'lorem', ''],
      ['unit5', '19 Dec 2024', 'lorem', ''],
    ],
  },
  English: {
    books: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Cambridge-Grammar-Book'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Meenakshi-Raman-and-Sangeeta-Sharma',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Wren-&-Martin---High-School-English-Grammar-and-Composition-Book-(Multicolour-Edition)-S.-Chand-Publishing-(2017)',
      ],
    ],
    'hand-written': [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Abbreviations-List'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'English-Tenses'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Idioms'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'indirect-speech-rules'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'johari'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'one-word-substitution'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Pronouns-Presentation'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'redundancies'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Tagore-Nationalism-1915'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'voice'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'words-often-confused'],
    ],
    syllabus: [],
    pyqs: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'engish-mid-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'engl-mid-2-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'english-end-4-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'english-end-sem'],
    ],
    yt: [
      ['unit1', '19 Dec 2024', 'lorem', ''],

      ['unit2', '19 Dec 2024', 'lorem', ''],

      ['unit3', '19 Dec 2024', 'lorem', ''],

      ['unit4', '19 Dec 2024', 'lorem', ''],
      ['unit5', '19 Dec 2024', 'lorem', ''],
    ],
  },
  Maths: {
    books: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'bs-grewal-book'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'bs-grewal'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'jaggi-mathur-2'],
    ],
    'hand-written': [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Beta-and-Gamma-Functions'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'chapter11diff-eq'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DE-Ex-10(a),(b),(c),(d)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'mathcom-u4'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Normal-distribution'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Numerical-method-1'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Numerical-methods-Unit-4'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Runge-Kutta-Method'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'some-polar-curves-list'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'u1-teacher-notes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Uniform-Distribution-'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Uniform-Distribution-1'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'UNIT-3-Mathematics--2-EIOT'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Unit-5-Probability-and-Statistics',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'unit4,-5-else'],
    ],
    syllabus: [['lorem ipsum', '19 Dec 2024', 'lorem', 'maths_2_syllabus']],
    pyqs: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'math-end-sem-2'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'maths-end-2-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'maths-mid-2-sem'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'maths-mid-sem'],
    ],
    yt: [
      [
        'unit1-a',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLZ9huVhPKZqdplonr7kqQApAykFgRqyrA',
      ],
      [
        'unit1-b',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLl4dU6GXOITKCgmbEN2u0I9w4IY8GjYmy',
      ],
      [
        'unit2-a',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLZ9huVhPKZqeFBTwU7D1lLeMKk6EdpwDm',
      ],
      [
        'unit2-b',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLhZ8YCwzpS2_mG1va-OpZpSDfLeWkffsP',
      ],
      [
        'unit3-a',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLZ9huVhPKZqeXygPlxsdTvc56GRmMPMQ4',
      ],
      [
        'unit3-b',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLhSp9OSVmeyLwtQbXv7VRXgoueSFaJGB4',
      ],
      [
        'unit4-a',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLZ9huVhPKZqempPZ57F8U8LYGSMOyqAyT',
      ],
      [
        'unit4-b',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLWSeGFM7wfNauIjDX98bXWTGicuEarsvz',
      ],
      [
        'unit5',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLUYiVTqE-dua3GaORJarjF92P0ZtBwCgD',
      ],
    ],
  },
  'wave-and-ocillation': {
    books: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'ajoy-ghatak-optics'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'AK-Jha'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DS-mathur'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'H-K-malik-enng-physics'],
    ],
    'hand-written': [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'diffraction'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'interference'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'laser-notes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Lasers'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Physics-Notes-1st-Sem-~-Vishu'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Physics-notes-of-OP-Thakur'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'polarisation-notes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'resolving-power'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Unit-1-(Oscillations-&-Waves)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Unit-2-(Wave-motion)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Unit-5-(Fibre-Optics)'],
    ],
    syllabus: [['lorem ipsum', '19 Dec 2024', 'lorem', 'syllabus_OWO']],
    pyqs: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', '2023-May'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', '2023-sept'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', '2023'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', '2024'],
    ],
    yt: [
      [
        'unit1',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PL7Ectyz3bMxPqQAJK5R6iGmRjX7U21mDg',
      ],

      [
        'unit2',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLSWDszNFa1Q3D66sah3KyZavKKhn8X8Tx',
      ],

      [
        'unit2-b',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLSWDszNFa1Q3D66sah3KyZavKKhn8X8Tx',
      ],
      [
        'unit3',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLU0SZIJ1umnkSHtOidNcWIegDQlbapIjF',
      ],

      [
        'unit4',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PL5zwY2E7i60XzRPOrKzvSzjvxnyK6jQB3',
      ],
      [
        'unit5',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLAPKGqvQGg6o8SJVVeZ3zdqaj37vdwR9j',
      ],
    ],
  },
  'network-analysis-and-synthesis': {
    books: [
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'intorduction-to-electronic-circuit-by-james-and-richard',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'nas-franklin-kuo'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'nas'],
    ],
    'hand-written': [
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        "ACAS-SENANI-SIR's-NOTES-COMPILED--(1)",
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'NAS-class-notes(Aakash)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Short-Notes'],
    ],
    syllabus: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Approved-NAS-Syllabus'],
    ],
    pyqs: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'nas-mid-sem-2019'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'nas-mid-sem-2024'],
    ],
    yt: [
      [
        'unit1',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PL7Ectyz3bMxOCfiVwb2OftmLhrDZQBXQj',
      ],

      ['unit2', '19 Dec 2024', 'lorem', ''],

      ['unit3', '19 Dec 2024', 'lorem', ''],

      ['unit4', '19 Dec 2024', 'lorem', ''],
      ['unit5', '19 Dec 2024', 'lorem', ''],
    ],
  },
  'electronic-device-and-circuit': {
    books: [
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Analog-Sedra-Smith-Microelectronic-Circuits-Oxford-University-Press-(2014)-7th-edition',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Balbir-kumar-book'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Boylestead-Nashelsky'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Electronic-Devices-and-Circuit-Theory-Robert-Boylestad-Louis-Nashelsky-7th-Edition',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'kupdf.net_microelectronic-circuits-by-sedra-and-smith-6th-edition-solutions-manualpdf',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Microelectronic-Circuits-7e-solution-manual',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'MOSFETs-Microelectronic_Circuits_by_Sedra_Smith',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Sedra---Microelectronic-Circuits-5th-Ed.---Solution-Manual',
      ],
    ],
    'hand-written': [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'CMOS-(2)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Depletion-MOSFET-(1)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'E-MOSFET'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'ECE-NOTES'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'EDC-Group-Assignment-combined'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'EDC-Lecture-Plan-1'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'edc-notes-1'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'EDC-notes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'EDC-Unit-1'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'EDC-Unit-2-(Harsh-Yadav)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'edc-unit-3-notes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'EEE-Notes-1st-Sem-~-Vishu-(1)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'EEE-Notes-1st-Sem-~-Vishu'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'EEE_analog'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'EEE_digital'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'electrical-notes'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Electronic-Devices-and-Circuits_Syllabus',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'ET-UNIT_2-PART-1'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'ET_UNIT_-2-PART-2..'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'ET_UNIT_-3-part-1'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'ET_UNIT_-3-part-2'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'ET_UNIT_1'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'FieldEffectTransistor'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'ICE-2-EDC-NOTES'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Important-topics-for-EDC'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'lec1_What-is-Semicondutor'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Lect-7_Varactor-Diode'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Lect-8_Schottky-diodes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Lect-9_Zener-Diodes-Numericals'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'lecture-1@edc'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'lecture-2@edc'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'lecture-3@edc'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'lecture-4@edc'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'lecture-5@edc'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'lecture-6@edc'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'lecture-7@edc'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'lecture@diode'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Lecture@zener-diode'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Lect_5_Mathematical-Analysis-of-Zener-Diode-Regulating-Circuit',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'led'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'MOSFET-Biasing'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'mosfet'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'n-channel-JFET..'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'New-Doc-2020-01-05-22.21.35'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'New-Doc-2020-03-03-18.53.10'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'notes_unit5'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'OpAmp'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'P-channel-JFET'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Parth-FET_s-Notes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'PN-Junction-Diode'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'SCR-notes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Sedra-S-Smith'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Transistor'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'U.1.Manish.EDC'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'U2.1.Manish.EDC'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'U2.2.Manish.EDC'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'U3.Manish.EDC'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'U4.1.Manish.EDC'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'U4.2.Manish.EDC'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Unit-1'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Unit-2-1'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Unit-2-ii'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Unit-2'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'UNIT-2_3'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Unit-4-EEE-Short-Notes-~-Vishu'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'UNIT-5-SHORT-NOTES'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Unit4--dc-motor'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'unit5'],
    ],
    syllabus: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'v3-final-Syllabus-EDC'],
    ],
    pyqs: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'edc-end-sem-2019'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'edc-end-sem-2024'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'edc-mid-sem-2024'],
    ],
    yt: [
      [
        'unit1-a',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLwjK_iyK4LLCoFeg8LpGiFkntVJ5R9URp',
      ],
      [
        'unit1-b',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLPLmXWcXdkUMfU1LNzjn4-Dh3I-zD9DOj',
      ],
      [
        'unit2',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLPLmXWcXdkUOJRfQWawWITPJEU7rS8cy6',
      ],

      [
        'unit3',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLPLmXWcXdkUNRJYeeVxZCAAHpl1BR5ZIX',
      ],

      [
        'unit4',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLPLmXWcXdkUPuVlVXDl1GukEu_wIihWWQ',
      ],
      [
        'unit5',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLPLmXWcXdkUOB6rgUtwTpVDd4bG6k6kjU',
      ],
    ],
  },
  DSA: {
    books: [
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'C++-Data-Structures-by--Nell-Dale',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Data.Structures-by-Gilberg-&-Forourzan',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-CLIFFORD-A.-SHAFFER'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-NARASIMHA-KARUMANCH'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'E.-Horowitz-and-S.-Sahani-DSA'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'Introduction-to-Algorithms-by-Cormen',
      ],
    ],
    'hand-written': [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Array'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Deque'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'ds'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-Notes--(1)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Graphs'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Heaps'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Inorder-Traversal'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Intro'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Linked-List-intro'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Mid-Sem-Solutions'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Post-Order-Traversal'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'PreOrder-Traversal'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Queue'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Quick-Sort'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Recursive-Function'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Singly-Linked-List'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Stack-and-Queue-(1)'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Stack-and-Queue'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Stack'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Tower-Of-Hanoi'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Tree-2'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Tree'],
    ],
    syllabus: [['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-Syllabus']],
    pyqs: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-END-SEM-2019-2'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-END-SEM-2019-Dec'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-END-SEM-2023-Dec'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-MID-SEM-2019-Dec'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-MID-SEM-2023-Sept'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-MID-SEM-2024-Feb'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'DSA-MID-SEM-sept-2019'],
    ],
    yt: [
      [
        'unit1',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PL2G8cXzxidYLNykymlcPlZVvSMqRsTiO3',
      ],

      [
        'unit2',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PL7Ectyz3bMxPdonczaicFayPa2FEPOuHW',
      ],

      [
        'unit3',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PL2G8cXzxidYLNykymlcPlZVvSMqRsTiO3',
      ],
      [
        'unit4-a',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PL2G8cXzxidYJFcvIz2SogogI_wzGBrosM',
      ],
      [
        'unit4-b',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PL7Ectyz3bMxMlf609oAFHebsZ4cjGLJ_q',
      ],
      [
        'unit5',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PL2G8cXzxidYILH26CW75dhmuubLzxj9r2',
      ],
    ],
  },
  CP: {
    books: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'programing-in-python-3'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'python-basic'],
    ],
    'hand-written': [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'binary-fh-book'],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'CheatSheet-Python-2_-Data-types',
      ],
      [
        'lorem ipsum',
        '19 Dec 2024',
        'lorem',
        'CheatSheet-Python-5_-Functions-and-Tricks',
      ],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'CP-Notes-1st-Sem~-Vishu'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'csv-fh-book'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'file-handling'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'list-qs'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'loop-qs'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'matplot'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'oop-IPEA'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'OOPS[1]'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Practice-Tuples'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Python_Complete_Notes'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'tuple-qs'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'txt-file-handling-book'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'Web_Development[1]'],
    ],
    syllabus: [['lorem ipsum', '19 Dec 2024', 'lorem', 'CP_SYLLABUS']],
    pyqs: [
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'cp-end-sem-'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'cp-end-sem-2018'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'cp-end-sem-2021'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'cp-end-sem-2023-2'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'cp-end-sem-2023'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'cp-end-sem-2024'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'cp-mid-sem-2020'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'cp-mid-sem-2022'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'cp-mid-sem-2023'],
      ['lorem ipsum', '19 Dec 2024', 'lorem', 'cp-mid-sem-2024'],
    ],
    yt: [
      [
        'unit1 (Videos = 3 to 18, 21 to 23,33,34)',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME',
      ],

      [
        'unit2  (Videos = 36,37,39,41,42,44,45,46,47,48,52-65,67-70,72-74)',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME',
      ],

      [
        'unit3',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLu0W_9lII9ahfRrhFcoB-4lpp9YaBmdCP',
      ],

      [
        'unit4  (Videos = 24,25,26,28,30,31)',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME',
      ],
      [
        'unit5  (Videos = 81,82,84-87,97,98)',
        '19 Dec 2024',
        'lorem',
        'https://www.youtube.com/playlist?list=PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME',
      ],
    ],
  },
}

export default data
