runtime: nodejs
env: flex

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '22'

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 50

readiness_check:
  path: '/'
  app_start_timeout_sec: 600
