# runtime: nodejs
# env: flex

# runtime_config:
#   operating_system: 'ubuntu22'
#   runtime_version: '20'
runtime: nodejs
env: flex

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '22'

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 50

readiness_check:
  path: '/'
  app_start_timeout_sec: 600

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
# runtime: nodejs22

# instance_class: F2

# env_variables:
#   NODE_ENV: 'production'

# handlers:
#   - url: /.*
#     script: auto
