import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Providers from '@/components/ProgressBarProvider'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import Toast from '@/components/Toast'

const poppins = Poppins({
  weight: ['300', '400', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='dark scroll-smooth'>
      <body className={poppins.className}>
        <Providers>
          <Toast />
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
